[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43
  adafruit/RTClib @ ^2.1.4
  milesburton/DallasTemperature @ ^4.0.5
  paulstoffregen/OneWire @ ^2.3.8

build_flags =
  -D USER_SETUP_LOADED
  -I include
  -include setup.h
